//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCI_213_Assingment3
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvisorTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AdvisorTable()
        {
            this.AppointmentTables = new HashSet<AppointmentTable>();
            this.StudentTables = new HashSet<StudentTable>();
        }
    
        public int AdvisorID { get; set; }
        public string AdvisorLastName { get; set; }
        public string AdvisorFirstName { get; set; }
        public string AdvisorUserName { get; set; }
        public string AdvisorLocation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTable> AppointmentTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentTable> StudentTables { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
