//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCI_213_Assingment3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppointmentDBEntities : DbContext
    {
        public AppointmentDBEntities()
            : base("name=AppointmentDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdvisorTable> AdvisorTables { get; set; }
        public virtual DbSet<AppointmentTable> AppointmentTables { get; set; }
        public virtual DbSet<MessagesTable> MessagesTables { get; set; }
        public virtual DbSet<StudentTable> StudentTables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    }
}
