//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSCI_213_Assingment3
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentTable()
        {
            this.AppointmentTables = new HashSet<AppointmentTable>();
        }
    
        public int StudentID { get; set; }
        public string StudentLastName { get; set; }
        public string StudentFistName { get; set; }
        public string StudentUserName { get; set; }
        public int StudentAdvisorID { get; set; }
    
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTable> AppointmentTables { get; set; }
        public virtual AdvisorTable AdvisorTable { get; set; }
    }
}
